config/routes.rb
Protrack::Application.routes.draw do

  get "client_track_session/:id/index" => "client_track_session#index",as: :client_track_session

  get "client_track_session/:eng_id/show/:track_id" => "client_track_session#show",as: :client_track_session_show

  get "client_track_session/:eng_id/edit/:track_id" => "client_track_session#edit",as: :client_track_session_edit

  get 'manage_urls/'=> "users#manage_urls", as: :manage_urls
  put 'update_manage_urls/'=> "users#update_manage_urls", as: :update_manage_urls

  get "client_track_session/:id/destroy" => "client_track_session#destroy"

  root :to => 'users#login'

  namespace :api do
    match 'user_signin', :to => 'user#user_login', :via => "post"
    match 'user/login', :to => 'user#coockies_user_login', :via => "post"
    match 'user/logout', :to => 'user#coockies_user_logout', :via => "post"

    match 'user_signup', :to => 'user#user_registeration', :via => "post"
    match 'need_update', :to => 'user#need_update', :via => "post"
    match 'user/update_push_token', :to => 'user#coockies_update_push_token', :via => "post"

    match 'load_file', :to => 'user_file#load_file', :via => "post"
    match 'save_file', :to => 'user_file#save_file', :via => "post"
    match 'register_device', :to => 'device#device_registeration', :via => "post"
    match 'get_track', :to => 'track#get_track', :via => "post"
    match 'data', :to => 'track#coockies_get_track', :via => "get"
    match 'turns/:id/note', :to => 'track#coockies_update_turns', :via => "patch"
    match 'register_purchased_track', :to => 'track#register_purchased_track', :via => "post"
    match 'get_purchased_track_tn_detail', :to => 'track#get_purchased_track_tn_detail', :via => "post"
    match 'restore_purchased_track', :to => 'track#restore_purchased_track', :via => "post"
    match 'restore_purchased_track_tn_detail', :to => 'track#restore_purchased_track_tn_detail', :via => "post"

    match 'reports', :to => 'report#coockies_post_report', :via => "post"
    match 'reports/:id', :to => 'report#coockies_patch_report', :via => "patch"
    match 'reports/:id', :to => 'report#coockies_delete_report', :via => "delete"
    match 'track/:id', :to => 'track#add_note', :via => "patch"
  end
  resources :race_engineer_reports

  match ':controller(/:action(/:id))(.:format)'
end

app/views/common/_common_header.html.erb
<div id="header">
<div style="float:left;"> <img src="/assets/design_images/logonew.png" width="337" height="112" class="logo" alt="ProManager V2.0" /> </div>
<div><span style="float:right; padding-top:10px; width:auto;"> Welcome <%= session[:user_name].to_s || "Un Known" %> / <a href="<%= url_for :action => 'logout', :controller => 'users' %>">Logout</a><br />
        <small>Last logged in at <strong><%= session[:last_logged].strftime("%m-%d-%Y %H:%M:%S") || "Not found" %> </strong> </small> 
		
		<% admin_id = session[:admin_id] || 0  %>
		<% if admin_id.to_i > 0  %>
			<% proxy_client_id = session[:proxy_client_id] || 0  %>
			<div style="clear:both;">&nbsp;</div>
			<div style="float:left; padding-top:2px;" >Change Client: &nbsp; </div><br/>
			<%= select_tag "proxy_client_id", options_from_collection_for_select(Client.get_all_client_list(), "id", "client_name",proxy_client_id), {:prompt => "--Change Client--", :id => "proxy_client_id" }%>
					
		<% end %>

        <% engn_id = session[:engn_id] || 0  %>
        <% if engn_id.to_i > 0  %>
            <div style="clear:both;">&nbsp;</div>
			<div style="float:left; padding-top:2px;" >Race Engineer Reports: &nbsp; </div><br/>
            <%= select_tag "proxy_race_engineer_id", options_from_collection_for_select(ClientTrack.get_all_client_tracks(), "id", "track_name"), {:prompt => "--Change Client Track--", :id => "proxy_race_engineer_id" }%>
        <% end %>
 </span>
</div>
</div>

<script type="text/javascript">

$(document).ready(function() {	  
	
	 $('#proxy_client_id').change(function() {
		 //alert("change select"); 
		var sel_client=$(this).val();			 
		 $("#middlepart").mask("Processing...");	
	    	
		 window.location.href = '/tracks/index/' + sel_client ;
      });
    $('#proxy_race_engineer_id').change(function() {
        //alert("change select");
        var set_client_track = $(this).val();
        $("#middlepart").mask("Processing...");

        window.location.href = '/race_engineer_reports/index/' + set_client_track ;
    });
	 
	
});

</script>

app/views/common/_common_menu.html.erb
<div id="menu" >
  <ul id="navmenu">
    <!-- <li style="float:right;" class="current"><a href="#">Visit Site</a></li> -->

    <% client_id = session[:client_id] || 0  %>
    <% admin_id = session[:admin_id] || 0  %>
    <% engn_id = session[:engn_id] || 0  %>
    <% proxy_client_id = session[:proxy_client_id] || 0  %>

    <% if (admin_id.to_i > 0 && proxy_client_id.to_i <= 0) || client_id.to_i > 0 %>
        <li><a class="proccessing" href="<%= url_for :controller => "dashboard", :action => "index" %>" title="Dashboard of Protrack Panel">Dashboard</a></li>
    <% end %>

    <% if (client_id.to_i > 0) %>
        <li><a  class="proccessing" href="<%= url_for :controller => "device_users", :action => "index" %>" title="Device user of Protrack Panel">Driver Accounts</a>
          <ul>
            <li><a  class="proccessing" href="<%= url_for :controller => "device_users", :action => "index" %>" title="View Device user of Protrack Panel">View Driver Accounts</a></li>
            <li><a  class="proccessing" href="<%= url_for :controller => "device_users", :action => "add" %>" title="Add new Device user of Protrack Panel">Add Driver Account </a></li>
          </ul>
        </li>
        <li><a  class="proccessing" href="<%= url_for :controller => "race_engineers", :action => "index" %>" title="Device user of Protrack Panel">Race Engineers</a>
          <ul>
            <li><a  class="proccessing" href="<%= url_for :controller => "race_engineers", :action => "index" %>" title="View Race Engineer of Protrack Panel">View Race Engineers</a></li>
            <li><a  class="proccessing" href="<%= url_for :controller => "race_engineers", :action => "add" %>" title="Add new Race Engineer of Protrack Panel">Add Race Engineer </a></li>
          </ul>
        </li>
    <% end %>

    <% if (admin_id.to_i > 0 && proxy_client_id.to_i > 0) %>
        <li><a  class="proccessing" href='<%= url_for :controller => "dashboard", :action => "back_to_admin" %>' title="Return to Admin of Protrack Panel">Back to Admin</a></li>
    <% end %>

    <% if (admin_id.to_i > 0 && proxy_client_id.to_i <= 0) %>
        <li><a  class="proccessing" href="<%= url_for :controller => "clients", :action => "index" %>" title="Clients of Protrack Panel">Clients</a>
          <ul>
            <li><a  class="proccessing" href="<%= url_for :controller => "clients", :action => "index" %>" title="View clients of Protrack Panel">View Clients</a></li>
            <li><a  class="proccessing" href="<%= url_for :controller => "clients", :action => "add" %>" title="Add new client of Protrack Panel">Add Client</a></li>
          </ul>
        </li>
    <% elsif (client_id.to_i > 0) %>
        <li><a  class="proccessing" href="<%= url_for :controller => "tracks", :action => "index" %>" title="Tracks of Protrack Panel">Tracks</a>
          <ul>
            <li><a  class="proccessing" href="<%= url_for :controller => "tracks", :action => "index" %>" title="View tracks of Protrack Panel">View Tracks</a></li>
            <li><a  class="proccessing" href="<%= url_for :controller => "tracks", :action => "add" %>" title="Add new track of Protrack Panel">Add Track</a></li>
          </ul>
        </li>
        <li><a  class="proccessing" href="<%= url_for :controller => "track_prices", :action => "index" %>" title="Track prices of Protrack Panel">Track Prices</a>
          <ul>
            <li><a  class="proccessing" href="<%= url_for :controller => "track_prices", :action => "index" %>" title="View track prices of Protrack Panel">View Track Prices</a></li>
            <li><a  class="proccessing" href="<%= url_for :controller => "track_prices", :action => "add" %>" title="Add new track price of Protrack Panel">Add Track price</a></li>
          </ul>
        </li>
        <!---  <li><a  class="proccessing" href="<%= url_for :controller => "track_turns", :action => "index" %>" title="Track turns of Protrack Panel">Track Turn</a>
							<ul>
								<li><a  class="proccessing" href="<%= url_for :controller => "track_turns", :action => "index" %>" title="view track turns of Protrack Panel">View Track Turns</a></li>                               
								<li><a  class="proccessing" href="<%= url_for :controller => "track_turns", :action => "add" %>" title="Add new track turns of Protrack Panel">Add Track Turn</a></li>  
								<li><a  class="proccessing" href="<%= url_for :controller => "track_turns", :action => "sort" %>" title="Sort track turns of Protrack Panel">Sort Track Turns</a></li>   								
							</ul>
					</li> -->
        <li title="Reports of Protrack Panel"><a>Reports</a>
          <ul>
            <li><a  class="proccessing" href="<%= url_for :controller => "reports", :action => "transaction_history" %>" title="Report of transactions history of Protrack Panel">Transactions History Report</a></li>
            <li><a  class="proccessing" href="<%= url_for :controller => "reports", :action => "restore_apps_history" %>" title="Report of restore apps of Protrack Panel">Restore Apps Report</a></li>
          </ul>
        </li>

    <% elsif (engn_id.to_i > 0) %>
        <li><a  class="proccessing" href="<%= url_for :controller => "track_sessions", :action => "index" %>" title="Track sessions of Protrack Panel">Track Sessions</a>
          <ul>
            <li><a  class="proccessing" href="<%= url_for :controller => "track_sessions", :action => "index" %>" title="View track sessions of Protrack Panel">View Track Sessions</a></li>
            <li><a  class="proccessing" href="<%= url_for :controller => "track_sessions", :action => "add" %>" title="Add new track session of Protrack Panel">Add Track Session</a></li>
          </ul>
        </li>
        <li>
          <%= link_to('Race Report', race_engineer_reports_path, :class => 'proccessing', :title => 'Race Report of Protrack Panel') %>
          <ul>
            <li><%= link_to('View Race Report', race_engineer_reports_path, :class => 'proccessing', :title => 'View Race Reports of Protrack Panel') %></li>
            <li><%= link_to('Add Race Report', new_race_engineer_report_path, :class => 'proccessing', :title => 'Add new Race Report of Protrack Panel') %></li>
          </ul>
        </li>
    <% end %>

    <% if (admin_id.to_i > 0 && proxy_client_id.to_i <= 0) || client_id.to_i > 0 %>
        <li title="Settings of Protrack Panel"><a>Settings</a>
          <ul>
            <li><a  class="proccessing" href="<%= url_for :controller => "users", :action => "change_profile" %>" title="Edit profile of Protrack Panel">Edit Profile</a></li>
            <li><a  class="proccessing" href="<%= url_for :controller => "users", :action => "change_password" %>" title="Change password of Protrack Panel">Change Password</a></li>
            <% if (admin_id.to_i > 0 && proxy_client_id.to_i <= 0) %>
                <li><%= link_to('Manage Urls', manage_urls_path, :class => 'proccessing', :title => 'Manage Urls') %></li>
            <% end %>
          </ul>
        </li>
    <% end %>
  </ul>
</div>

app/views/common/error.html.erb
<div class="<%= t @error_code.to_s + '.class' %>">
	<% if (t @error_code.to_s + '.title').strip.empty? == false  %>
		<span><%= t @error_code.to_s + '.title' %></span>
		<p><%= t @error_code.to_s + '.desc' %></p>
	<% else %>	
	  	<label><%= t @error_code.to_s + '.desc' %></label>
	<% end %>	
</div>
<% # Below code for auto hide flash message only success %>
<% if (t @error_code.to_s + '.class') == 'success' %>
<script>
$(".success").fadeOut(6000);
</script>
<% end %>