config/routes.rb
Protrack::Application.routes.draw do

  get "client_track_session/:id/index" => "client_track_session#index",as: :client_track_session

  get "client_track_session/:eng_id/show/:track_id" => "client_track_session#show",as: :client_track_session_show

  get "client_track_session/:eng_id/edit/:track_id" => "client_track_session#edit",as: :client_track_session_edit

  get 'manage_urls/'=> "users#manage_urls", as: :manage_urls
  put 'update_manage_urls/'=> "users#update_manage_urls", as: :update_manage_urls

  get "client_track_session/:id/destroy" => "client_track_session#destroy"

  root :to => 'users#login'

  namespace :api do
    match 'user_signin', :to => 'user#user_login', :via => "post"
    match 'user/login', :to => 'user#coockies_user_login', :via => "post"
    match 'user/logout', :to => 'user#coockies_user_logout', :via => "post"

    match 'user_signup', :to => 'user#user_registeration', :via => "post"
    match 'need_update', :to => 'user#need_update', :via => "post"
    match 'user/update_push_token', :to => 'user#coockies_update_push_token', :via => "post"

    match 'load_file', :to => 'user_file#load_file', :via => "post"
    match 'save_file', :to => 'user_file#save_file', :via => "post"
    match 'register_device', :to => 'device#device_registeration', :via => "post"
    match 'get_track', :to => 'track#get_track', :via => "post"
    match 'data', :to => 'track#coockies_get_track', :via => "get"
    match 'turns/:id/note', :to => 'track#coockies_update_turns', :via => "patch"
    match 'register_purchased_track', :to => 'track#register_purchased_track', :via => "post"
    match 'get_purchased_track_tn_detail', :to => 'track#get_purchased_track_tn_detail', :via => "post"
    match 'restore_purchased_track', :to => 'track#restore_purchased_track', :via => "post"
    match 'restore_purchased_track_tn_detail', :to => 'track#restore_purchased_track_tn_detail', :via => "post"

    match 'reports', :to => 'report#coockies_post_report', :via => "post"
    match 'reports/:id', :to => 'report#coockies_patch_report', :via => "patch"
    match 'reports/:id', :to => 'report#coockies_delete_report', :via => "delete"
    match 'track/:id', :to => 'track#add_note', :via => "patch"
  end
  resources :race_engineer_reports

  match ':controller(/:action(/:id))(.:format)'
end

app/models/race_engineer_report.rb
class RaceEngineerReport < ActiveRecord::Base
  # attr_accessible :engineer_name, :race_engineer_id, :client_id

  belongs_to :race_engineer
  belongs_to :client

  validates :name, :presence => {:message => I18n.t('presence') }

  validates :report_date, :presence => {:message => I18n.t('presence') }
  validates :driver_id, :presence => {:message => I18n.t('presence') }
  validates :engineer_name, :presence => {:message => I18n.t('presence') }
  validates :championship, :presence => {:message => I18n.t('presence') }
  validates :circuit, :presence => {:message => I18n.t('presence') }
  validates :event, :presence => {:message => I18n.t('presence') }

  validates :name, :uniqueness => {:scope => :client_id, :message => I18n.t('uniqueness') }
end

app/controllers/race_engineer_reports_controller.rb
class RaceEngineerReportsController < ApplicationController
  skip_before_filter :require_login, :only => [:update]
  require 'fileutils'

  def index
    record_per_page=Protrack::Configuration['pagesize']
    if params[:id]
      @race_engineer_reports = RaceEngineerReport.where('circuit = ? ', params[:id]).paginate(:per_page => record_per_page, :page => params[:page])
    else
      @race_engineer_reports = RaceEngineerReport.paginate(:per_page => record_per_page, :page => params[:page])
    end
  end

  def new
    race_engineer = RaceEngineer.find(session[:engn_id])
    @race_engineer_report = RaceEngineerReport.new() do |race_report|
      race_report.race_engineer_id = race_engineer.id if race_engineer
      race_report.client_id = race_engineer.fk_client_id if race_engineer
      race_report.engineer_name = session[:user_name].to_s
      race_report.report_date = Date.today.to_s
    end
  end

  def create
    abort params.inspect
  end

  def create_ajax
    # begin
      # abort params.inspect
      @race_engineer_report = RaceEngineerReport.new(params[:race_engineer_report])
      @race_engineer_report.engineer_name = session[:user_name].to_s
      @race_engineer_report.create_ip=request.remote_ip
      @race_engineer_report.last_updated_ip=request.remote_ip
      @race_engineer_report.status_code=401

      unless params[:race_engineer_report][:report_info].nil?
        track_image_filename_=params[:race_engineer_report][:report_info].original_filename.to_s
        track_img_name=track_image_filename_.split('/').last
        track_img_extn=track_img_name.split('.').last
        if @race_engineer_report.race_engineer.race_engineer_name.nil?
          track_newfilename = "Report_info_pdf_#{(Time.now.strftime('%y%m%d'))}}"
        else
          track_newfilename = "Report_info_pdf_#{(Time.now.strftime('%y%m%d'))}_#{@race_engineer_report.race_engineer.race_engineer_name.split(' ').join('_') }"
        end
        track_newfilename = track_newfilename + '.' + track_img_extn
        report_info_pdf_path="/assets/images/client/client_" + @race_engineer_report.client_id.to_s + "/report_info_pdf/"
        save_file_url(params[:race_engineer_report][:report_info],track_newfilename, report_info_pdf_path)
        public_url_image_path="/assets/client/client_" + @race_engineer_report.client_id.to_s + "/report_info_pdf/"

        @race_engineer_report.report_info= public_url_image_path + track_newfilename

      end

      if @race_engineer_report.valid?
        if @race_engineer_report.save!
          render :json => {:resp_code => "200", :message => I18n.t(:race_report_created)}
          return
        else
          render :json => {:resp_code => "402", :message => I18n.t(:race_report_invalid)}
          return
        end
      else
        error_messages=""
        if @race_engineer_report.errors.full_messages.length >0
          @race_engineer_report.errors.full_messages.each do |msg|
            if error_messages.empty? == false
              error_messages =  error_messages + ", \n "
            else
              error_messages =  error_messages + " \n "
            end
            error_messages =  error_messages +  msg
          end
        end
        render :json => {:resp_code => "401", :message => error_messages}
        return
      end
    # rescue => ex
      logger.error "erro: #{ex.class} , #{ex.message}"
      render :json => {:resp_code => "403", :message => I18n.t(:race_report_invalid)}
      return
    # end
    render :json => {:resp_code => "404", :message => I18n.t(:race_report_invalid)}
  end


  def edit
   @race_engineer_report =  RaceEngineerReport.find(params[:id])
  end
  def update
   @race_engineer_report = RaceEngineerReport.find(params[:id])

   unless params[:race_engineer_report][:report_info].nil?
     track_image_filename_=params[:race_engineer_report][:report_info].original_filename.to_s
     track_img_name=track_image_filename_.split('/').last
     track_img_extn=track_img_name.split('.').last
     if @race_engineer_report.race_engineer.race_engineer_name.nil?
       track_newfilename = "Report_info_pdf_#{(Time.now.strftime('%y%m%d'))}}"
     else
       track_newfilename = "Report_info_pdf_#{(Time.now.strftime('%y%m%d'))}_#{@race_engineer_report.race_engineer.race_engineer_name.split(' ').join('_') }"
     end
     track_newfilename = track_newfilename + '.' + track_img_extn
     report_info_pdf_path="/assets/images/client/client_" + @race_engineer_report.client_id.to_s + "/report_info_pdf/"
     save_file_url(params[:race_engineer_report][:report_info],track_newfilename, report_info_pdf_path)
     public_url_image_path="/assets/client/client_" + @race_engineer_report.client_id.to_s + "/report_info_pdf/"

     params[:race_engineer_report][:report_info]= @race_engineer_report_path =  public_url_image_path + track_newfilename
   end

   @race_engineer_report.update_attributes(params[:race_engineer_report], report_info: @race_engineer_report_path)

   redirect_to :action => 'index'
  end

  def show
    @race_engineer_report =  RaceEngineerReport.find(params[:id])
  end

  def destroy
    RaceEngineerReport.destroy(params[:id])
    redirect_to :action => 'index'
  end

  def save_file_url(params_name,filename, path)
    begin
      dir= File.join(Rails.root, "app", path)
      FileUtils::mkdir_p dir unless File.exists?(dir)

      path = File.join(Rails.root, "app", path, filename)
      # write the file
      File.open(path, "wb") { |f| f.write(params_name.read) }
    rescue => ex
      logger.info "erro: #{ex.class} , #{ex.message}"
    end
  end

end

app/helpers/race_engineer_reports_helper.rb
module RaceEngineerReportsHelper
end

app/views/race_engineer_reports/edit.html.erb
<%= javascript_include_tag "jquery.MultiFile.js" %>

<style>
	.MultiFile-list{
		padding-bottom: 2px;
		padding-left: 160px;
		padding-right: 0;
		padding-top: 5px;}

	.MultiFile-label{
		padding-top: 5px;
	}

</style>

<%= form_for @race_engineer_report, :url =>  {:action => "update"}, html: { method: :put } do |f| %>

	<div id="error_div"></div>
	<% if @race_engineer_report.errors.full_messages.length >0 %>
		<div class="error">
		  <% @race_engineer_report.errors.full_messages.each_with_index do |msg, index| %>
			  <p><%= "#{index+1}) #{msg}" %></p>
		  <% end %>
		</div>
	<% end %>

	<fieldset>
	  <legend><%= t :EditRaceReport %></legend>
	  <%= f.hidden_field :race_engineer_id %>
	  <%= f.hidden_field :client_id %>

	  <label><%= t :ReportName %>: </label>
	  <%= f.text_field :name, :class => "narrow", :style => "width:30% !important;"  %>
	  <br />

	  <label><%= t :Date %>: </label>
	  <%= f.text_field :report_date, :class => "narrow", :style => "width:10% !important;"  %>
	  <br />


	  <label><%= t :Driver %>: </label>
	  <%= f.select :driver_id, DeviceUser.get_device_user_list(@race_engineer_report.client_id).collect {|m| [m.name, m.id] }, {:prompt => t('Driver'), :id => "driver_id"}, :style => "margin-top:5px;"  %>
	  <br />

	  <label><%= t :EngineerName %>: </label>
	  <%= f.text_field :engineer_name, :disabled => true, :class => "narrow", :style => "width:30% !important; readonly:true;"  %>
	  <br />

	  <label><%= t :Championship %>: </label>
	  <%= f.text_field :championship, :class => "narrow", :style => "width:60% !important;"  %>
	  <br />

	  <label><%= t :Circuit %>: </label>
	  <%= f.select :circuit, ClientTrack.all.collect{|track| [track.track_name, track.id]}, {:prompt => "-- SELECT --"}, :style => "margin-top:5px;"  %>
	  <br />

	  <label><%= t :Event %>: </label>
	  <%= f.text_field :event, :class => "narrow", :style => "width:60% !important;"  %>
	  <br />

	  <label><%= t :ReportInfo %>: </label>
	  <%#= f.text_area :report_info, :class => "narrow", :style => "width:60% !important; height: 75px;"  %>
	  <%= @race_engineer_report.report_info.split('/').last unless @race_engineer_report.report_info.nil? %>
	  <%= f.file_field :report_info, :height => "80px;", :width => "80px", :accept => "application/pdf" %>

	  <br />

	  <label ></label>
	  <!--<input  class="green"  type="button" value="<%#= t :Save %>" id="edit_race_engineer_report" tabindex="4" />-->
	  <%= f.submit 'Save', class: 'green' %>
	  <input  class="gray"  type="reset" value="<%= t :Reset %>" id="reset_form" tabindex="5" />

	  <a href="<%= url_for :action => "index" %>" tooltip="<%= t :Index %>" >
		<input  class="red proccessing"  type="button" value="<%= t :Cancel %>" id="cancel_track" tabindex="5" />
	  </a>

	</fieldset>

<% end %>

<script type="text/javascript">

	$(document).ready(function(){
		$( "#race_engineer_report_report_date" ).datepicker();
		$( "#race_engineer_report_report_date" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
		$('#race_engineer_report_report_date').attr('value', "<%= @race_engineer_report.report_date %>");

		$('#client_track_no_turns').change(function(){
			if(parseInt(this.value).toFixed(0) == 'NaN')
				this.value = "";
			else
				this.value = parseInt(this.value).toFixed(0);
		});

		$("#new_race_engineer_report").ajaxStop(function(){
			$("#middlepart").unmask();
		});

		$(".proccessing").click(function(){
			$("#middlepart").mask("Processing...");
		});

		$("#reset_form").click(function(){
			$("#race_engineer_report_session_image_wrap_list").html('');
			return true;
		});

		$("#edit_race_engineer_report").click(function(){
			$("#middlepart").mask("Processing...");

			// var  oOutput = document.getElementById("new_client_track"),
			oData = JSON.stringify($('form').serializeArray());
			$.ajax({
				url: '/race_engineer_reports/'+<%= @race_engineer_report.id %>,
				type: 'PUT',
				dataType: 'jsonp',
				data: oData
			}).done(function(oEvent) {

				$("#error_div").html('');
				$("#error_div").removeClass('error');
				var data=jQuery.parseJSON(oReq.response);
				if(data.resp_code == "200")
				{
					window.location.href = "<%= url_for :action => "index" %>";
				}
				else
				{
					messages = data.message.split(",");
					$.each(messages,function(i){
//                        alert(i);
						$("#error_div").append("<p>" + parseInt(i+1) + ". " + messages[i] + "</p>");
					});
					$("#error_div").addClass('error');
					$("#middlepart").unmask();
				}
			});


//			var oReq = new XMLHttpRequest();
//			oReq.open("PUT", "<%#= url_for :action => "update", id: @race_engineer_report.id %>", true);
//			oReq.onload = function(oEvent) {
//				alert('success')
//
//				$("#error_div").html('');
//				$("#error_div").removeClass('error');
//				var data=jQuery.parseJSON(oReq.response);
//				if(data.resp_code == "200")
//				{
//					window.location.href = "<%#= url_for :action => "index" %>";
//				}
//				else
//				{
//					messages = data.message.split(",");
//					$.each(messages,function(i){
////                        alert(i);
//						$("#error_div").append("<p>" + parseInt(i+1) + ". " + messages[i] + "</p>");
//					});
//					$("#error_div").addClass('error');
//					$("#middlepart").unmask();
//				}

//			};
//			oReq.send(oData);
		});

	});
</script>

app/views/race_engineer_reports/index.html.erb
<div style="padding-bottom: 20px">
  <!--<a class="publish proccessing" href="<%#= url_for :action => "add" %>"><%#= t :AddTrackSession %> </a>-->
  <%= link_to 'Add Engineer Report', new_race_engineer_report_path, class: "publish proccessing" %>
</div>
<table cellspacing="0" cellpadding="0" width="100%" class="listing" id="race_engineer_reports_listing"  >
  <thead>
  <tr>
    <th class="capt" colspan="4">
      <%= t :RaceEngineerReport %>
    </th>

  </tr>

  <tr class="ftr">
    <th style="text-align:left;">
      <%= t('ReportName') %>
    </th>
    <th style="text-align:left;">
      <%= t('ReportLastMod') %>
    </th>
    <th>
      <%= t('Action') %>
    </th>
  </tr>
  </thead>

  <% alt_row=0 %>
  <% sr_no=0 %>
  <% if @race_engineer_reports.nil? || @race_engineer_reports.count == 0  %>
      <tr>
        <td colspan="4" style="border: none;"><%= t :NoRecordFound %></td>
      </tr>
  <% else %>
      <% @race_engineer_reports.each do |f| %>
          <% if alt_row==0 %>
              <% alt_row=1 %>
              <tr id="node-<%= f.id %>">
          <% else %>
              <tr id="node-<%= f.id %>" class="tb_grey">
                <% alt_row=0 %>
          <% end %>
          <td  align="center" valign="middle">
            <div id="name<%= f.id %>" class="" style="text-align:left;">
              <%= f.report_date.to_formatted_s(:long) %> - <%= f.engineer_name %> - <%= f.championship %> - <%= f.circuit %> - <%= f.event %>
            </div>
          </td>
          <td  align="center" valign="middle">
            <div id="last_updated_at_<%= f.id %>" class="" style="text-align:left;">
              <%= f.updated_at.strftime("%m-%d-%Y %H:%M:%S") %>
            </div>
          </td>
          <td  align="center" valign="middle">
            <div id="action_<%= f.id %>" class="" style="">
              <%= link_to(t(:Edit), edit_race_engineer_report_path(f.id), :class => "edit proccessing")%>
              <%= link_to(t(:View), race_engineer_report_path(f.id), :class => "publish proccessing")%>
              <%= link_to(t(:Delete), race_engineer_report_path(f.id), :confirm => 'Are you sure ?', :method => :delete, :class => "delete proccessing")%>
            </div>
          </td>

          </tr>
      <% end %>
  <% end %>
  <tfoot>
  <tr>
    <th colspan="5" class="ftr bgr">
      <div class="paging_cntr">
        <!--start  Pagination -->
        <% if @race_engineer_reports.count > 0 %>
            <div style="float:right;  margin-right:15px;"><%=  will_paginate @race_engineer_reports %>
            </div>
        <% end %>
        <!-- end Pagination -->
      </div>
    </th>
  </tr>
  </tfoot>


</table>
<!-- End cs_slider -->
<%=hidden_field_tag "pageno", params[:page]%>

app/views/race_engineer_reports/new.html.erb
<%= javascript_include_tag "jquery.MultiFile.js" %>

<style>
    .MultiFile-list{
        padding-bottom: 2px;
        padding-left: 160px;
        padding-right: 0;
        padding-top: 5px;}

    .MultiFile-label{
        padding-top: 5px;
    }

</style>

<%= form_for @race_engineer_report, :url =>  {:action => "create"} do |f| %>

    <div id="error_div"></div>
    <% if @race_engineer_report.errors.full_messages.length >0 %>
        <div class="error">
          <% @race_engineer_report.errors.full_messages.each_with_index do |msg, index| %>
              <p><%= "#{index+1}) #{msg}" %></p>
          <% end %>
        </div>
    <% end %>

    <fieldset>
      <legend><%= t :AddRaceReport %></legend>
      <%= f.hidden_field :race_engineer_id %>
      <%= f.hidden_field :client_id %>

      <label><%= t :ReportName %>: </label>
      <%= f.text_field :name, :class => "narrow", :style => "width:30% !important;"  %>
      <br />

      <label><%= t :Date %>: </label>
      <%= f.text_field :report_date, :class => "narrow", :style => "width:10% !important;"  %>
      <br />


      <label><%= t :Driver %>: </label>
      <%= f.select :driver_id, DeviceUser.get_device_user_list(@race_engineer_report.client_id).collect {|m| [m.name, m.id] }, {:prompt => t('Driver'), :id => "driver_id"}, :style => "margin-top:5px;"  %>
      <br />

      <label><%= t :EngineerName %>: </label>
      <%= f.text_field :engineer_name, :disabled => true, :class => "narrow", :style => "width:30% !important; readonly:true;"  %>
      <br />

      <label><%= t :Championship %>: </label>
      <%= f.text_field :championship, :class => "narrow", :style => "width:60% !important;"  %>
      <br />

      <label><%= t :Circuit %>: </label>
      <%= f.select :circuit, ClientTrack.all.collect{|track| [track.track_name, track.id]}, {:prompt => "-- SELECT --"}, :style => "margin-top:5px;"  %>
      <br />

      <label><%= t :Event %>: </label>
      <%= f.text_field :event, :class => "narrow", :style => "width:60% !important;"  %>
      <br />

      <label><%= t :ReportInfo %>: </label>
      <%#= f.text_area :report_info, :class => "narrow", :style => "width:60% !important; height: 75px;"  %>
      <%= f.file_field :report_info, :height => "80px;", :width => "80px", :accept => "application/pdf" %>

      <br />

      <label ></label>
      <input  class="green"  type="button" value="<%= t :Save %>" id="create_race_engineer_report" tabindex="4" />
      <input  class="gray"  type="reset" value="<%= t :Reset %>" id="reset_form" tabindex="5" />

      <a href="<%= url_for :action => "index" %>" tooltip="<%= t :Index %>" >
        <input  class="red proccessing"  type="button" value="<%= t :Cancel %>" id="cancel_track" tabindex="5" />
      </a>

    </fieldset>

<% end %>

<script type="text/javascript">

    $(document).ready(function(){
        $( "#race_engineer_report_report_date" ).datepicker();
        $( "#race_engineer_report_report_date" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
        $('#race_engineer_report_report_date').attr('value', "<%= @race_engineer_report.report_date %>");

        $('#client_track_no_turns').change(function(){
            if(parseInt(this.value).toFixed(0) == 'NaN')
                this.value = "";
            else
                this.value = parseInt(this.value).toFixed(0);
        });

        $("#new_race_engineer_report").ajaxStop(function(){
            $("#middlepart").unmask();
        });

        $(".proccessing").click(function(){
            $("#middlepart").mask("Processing...");
        });

        $("#reset_form").click(function(){
            $("#race_engineer_report_session_image_wrap_list").html('');
            return true;
        });

        $("#create_race_engineer_report").click(function(){
            $("#middlepart").mask("Processing...");

            // var  oOutput = document.getElementById("new_client_track"),
            oData = new FormData(document.forms.namedItem("new_race_engineer_report"));

            var oReq = new XMLHttpRequest();
            oReq.open("POST", "<%= url_for :action => "create_ajax" %>", true);
            oReq.onload = function(oEvent) {

                $("#error_div").html('');
                $("#error_div").removeClass('error');
                var data=jQuery.parseJSON(oReq.response);
                if(data.resp_code == "200")
                {
                    window.location.href = "<%= url_for :action => "index" %>";
                }
                else
                {
                    messages = data.message.split(",");
                    $.each(messages,function(i){
//                        alert(i);
                        $("#error_div").append("<p>" + parseInt(i+1) + ". " + messages[i] + "</p>");
                    });
                    $("#error_div").addClass('error');
                    $("#middlepart").unmask();
                }

            };
            oReq.send(oData);
        });

    });
</script>

app/views/race_engineer_reports/show.html.erb
<style>
.edit_session_image{
background-color: #808080;
    float: left;
    margin-bottom: 5px;
    margin-left: 0px;
    margin-right: 5px;
    margin-top: 5px;
    padding-bottom: 5px;
    padding-left: 5px;
    padding-right: 5px;
    padding-top: 5px;
}

.remove_session_image{
	cursor: pointer;
}

.MultiFile-list{
		padding-bottom: 2px;
		padding-left: 160px;
		padding-right: 0;
		padding-top: 5px;}

		.MultiFile-label{
			padding-top: 5px;
		}


</style>

<%= form_for @race_engineer_report, :url =>  {:action => "index", :id => @race_engineer_report.id} do |f| %>

	<fieldset>
		<!--<legend> View Engineer Report </legend>-->

	  <legend><%= t :ViewRaceReport %></legend>

	  <label><%= t :ReportName %>: </label>
	  <%= f.text_field :name, :class => "narrow", :style => "width:30% !important;", disabled: true  %>
	  <br />

	  <label><%= t :Date %>: </label>
	  <%= f.text_field :report_date, :class => "narrow", :style => "width:10% !important;", disabled: true  %>
	  <br />


	  <label><%= t :Driver %>: </label>
	  <%= f.select :driver_id, DeviceUser.get_device_user_list(@race_engineer_report.client_id).collect {|m| [m.name, m.id] }, {:prompt => t('Driver'), :id => "driver_id"}, :style => "margin-top:5px;", disabled: true  %>
	  <br />

	  <label><%= t :EngineerName %>: </label>
	  <%= f.text_field :engineer_name, :disabled => true, :class => "narrow", :style => "width:30% !important; readonly:true;"  %>
	  <br />

	  <label><%= t :Championship %>: </label>
	  <%= f.text_field :championship, :class => "narrow", :style => "width:60% !important;", disabled: true  %>
	  <br />

	  <label><%= t :Circuit %>: </label>
	  <%= f.select :circuit, ClientTrack.all.collect{|track| [track.track_name, track.id]}, {:prompt => "-- SELECT --"}, :style => "margin-top:5px;", disabled: true  %>
	  <br />

	  <label><%= t :Event %>: </label>
	  <%= f.text_field :event, :class => "narrow", :style => "width:60% !important;", disabled: true  %>
	  <br />

	  <label><%= t :ReportInfo %>: </label>
	  <%= f.text_field :report_info, :class => "narrow", :style => "width:60% !important;", disabled: true  %>
	  <br />

		<br style="clear:both;" />

		<label ></label>
	  <a href="<%= url_for :action => "edit", :id => @race_engineer_report.id %>" tooltip="<%= t :Edit %>"  >
		<input class="green proccessing" type="button" value="<%= t :Edit %>" id="edit_session" tabindex="5" style="margin-top:5px;" />
	  </a>
	  <a href="<%= url_for :action => "destroy", :id => @race_engineer_report.id %>" tooltip="<%= t :Delete %>" data-method="delete" data-confirm="Are you sure ?">
		<input class="gray proccessing"  type="button" value="<%= t :Delete %>" id="delete_session" tabindex="5" />
	  </a>

	  <a href="<%= url_for :action => "index" %>" tooltip="<%= t :Index %>" >
		<input  class="red proccessing" type="button" value="<%= t :Cancel %>" id="cancel_session" tabindex="5" />
	  </a>

	</fieldset>

<% end %>

<script type="text/javascript">
$(document).ready(function() {	
  
   $(".proccessing").click(function(){	
	  	$("#middlepart").mask("Processing...");	
	  });
});
</script>